### ISSUE TITLE
No license specified?

### ISSUE THREAD

**Issue by ryuslash** [katusk/CMakeNuGetTools#1]
Hi there!

I was wondering what the intended license for this project is. I see no mention of any license in the readme or in any files in the repository. I'd like to use it, but I can't without an explicit license.

Thanks in advance!

Cheers,

Tom

**Comment by katusk** [comment]
Hi Tom, sure, I can throw in a license. Which type of license do you want? ;o) I would be most happy if this proves to be useful for anyone else. For me any one of the "do as you want, and modify it as you want freely" type licenses are fine. Maybe [Beerware](https://en.wikipedia.org/wiki/Beerware)? Cheers, Kristóf

**Comment by katusk** [comment]
On a more serious note, I just quickly checked [choosealicense.com](https://choosealicense.com/), and the MIT license looks permissive enough. It would be great if anyone could use it without unnecessary restrictions. I worked for bigger companies before, and I do not want to unnecessarily mess around with programmers who are working for a big company now (so closed source versions etc are fine for me, just use it as you want really). What do you think?

**Comment by ryuslash** [comment]
Hey Kristóf,

Thanks for getting back to me :) I am actually looking to use your project at work, so something like MIT license would definitely make that easier. It's your project however, you need to decide under which terms you wish to distribute it. I really can't tell you, or even ask you, which specific license to pick.

**Comment by katusk** [comment]
OK, I decided to distribute CMakeNuGetTools under the MIT license. Hang on, gonna add it in a jiffy.

**Comment by katusk** [comment]
OK, there you have it, enjoy :) Closing this issue.

PS There are a few minor issues with the scripts known to me that is not affecting my use-cases right now, but might affect yours. I am going to create new issues (probably over the weekend) to track those and to be more transparent. I will fix them sometime for sure...

**Comment by ryuslash** [comment]
Thank you!

So far I haven't run into any issue, so hopefully I won't :)
